import { useEffect, useMemo, useRef, useState, type KeyboardEvent as ReactKeyboardEvent } from 'react';
import { AlertTriangle, ChevronDown, RefreshCw, X } from 'lucide-react';
import dayjs from 'dayjs';
import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle
} from '@/components/ui/alert-dialog';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Checkbox } from '@/components/ui/checkbox';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { panelTokens } from '@/components/layout/panel-tokens';
import { resolveGroupPermissionState } from '@/lib/groups/group-filtering';
import { lintTemplate } from '@/lib/templates/render-template';
import { useCampaignStore } from '@/stores/use-campaign-store';
import { useActivityLogStore } from '@/stores/use-activity-log-store';
import { useComposerStore } from '@/stores/use-composer-store';
import { useGroupsStore } from '@/stores/use-groups-store';
import { useSettingsStore } from '@/stores/use-settings-store';

const buildCampaignName = (): string => `campaign-${dayjs().format('YYYYMMDD-HHmmss')}`;
const AUTO_CAMPAIGN_NAME_REGEX = /^campaign-\d{8}-\d{6}$/;
const isAutoGeneratedCampaignName = (value: string): boolean =>
  AUTO_CAMPAIGN_NAME_REGEX.test(value.trim());

const buildCampaignNameFromSource = (sourceName: string): string => {
  const normalized = sourceName.trim();
  if (!normalized) {
    return buildCampaignName();
  }
  return normalized;
};

const GROUP_CHAT_ID_REGEX = /^[0-9a-z._:-]+@g\.us$/i;
const normalizeChatId = (chatId: string): string => chatId.trim().toLowerCase();

const parseChatIds = (value: string): { validChatIds: string[]; invalidTokens: string[] } => {
  const tokens = value
    .split(/[\n,;\s]+/)
    .map((item) => item.trim())
    .filter(Boolean);

  const validSet = new Set<string>();
  const invalidTokens: string[] = [];
  for (const token of tokens) {
    const normalized = normalizeChatId(token);
    if (GROUP_CHAT_ID_REGEX.test(normalized)) {
      validSet.add(normalized);
      continue;
    }
    invalidTokens.push(token);
  }

  return {
    validChatIds: Array.from(validSet),
    invalidTokens
  };
};

const sanitizeInt = (value: number, fallback: number, min = 0): number => {
  if (!Number.isFinite(value)) {
    return fallback;
  }
  return Math.max(min, Math.floor(value));
};

export function OperationsPanel(): JSX.Element {
  const [confirmOpen, setConfirmOpen] = useState(false);
  const [dryRun, setDryRun] = useState(true);
  const [confirmDuplicateWarning, setConfirmDuplicateWarning] = useState<string | null>(null);
  const [campaignName, setCampaignName] = useState(buildCampaignName());
  const [showAdvanced, setShowAdvanced] = useState(false);
  const [blacklistInput, setBlacklistInput] = useState('');
  const lastLoadedAtRef = useRef<string | null>(null);

  const settings = useSettingsStore((state) => state.settings);
  const badgeState = useSettingsStore((state) => state.badgeState);
  const pushUiLog = useActivityLogStore((state) => state.pushUiLog);
  const groups = useGroupsStore((state) => state.groups);
  const selectedIdsSet = useGroupsStore((state) => state.selectedIds);
  const composer = useComposerStore();
  const campaignStore = useCampaignStore();

  const selectedIds = useMemo(() => Array.from(selectedIdsSet), [selectedIdsSet]);
  const selectedCount = selectedIds.length;
  const controlsDisabled = campaignStore.running || campaignStore.stopping;
  const campaignPaused = campaignStore.paused;
  const campaignStopping = campaignStore.stopping;
  const groupNameByChatId = useMemo(() => {
    const mapping = new Map<string, string>();
    groups.forEach((group) => {
      const normalizedId = normalizeChatId(group.chatId);
      const normalizedName = group.name.trim();
      if (!normalizedId || !normalizedName || mapping.has(normalizedId)) {
        return;
      }
      mapping.set(normalizedId, normalizedName);
    });
    return mapping;
  }, [groups]);
  const selectedGroups = useMemo(
    () => groups.filter((group) => selectedIdsSet.has(group.chatId)),
    [groups, selectedIdsSet]
  );
  const blockedIds = useMemo(
    () => new Set(campaignStore.config.blacklist.map((item) => normalizeChatId(item))),
    [campaignStore.config.blacklist]
  );
  const effectiveTargets = useMemo(
    () =>
      campaignStore.config.whitelistMode
        ? selectedGroups.filter((group) => blockedIds.has(normalizeChatId(group.chatId)))
        : selectedGroups.filter((group) => !blockedIds.has(normalizeChatId(group.chatId))),
    [blockedIds, campaignStore.config.whitelistMode, selectedGroups]
  );
  const effectiveTargetCount = effectiveTargets.length;
  const permissionBlockedTargets = useMemo(
    () => effectiveTargets.filter((group) => resolveGroupPermissionState(group) === 'blocked'),
    [effectiveTargets]
  );
  const permissionBlockedCount = permissionBlockedTargets.length;
  const permissionAllowedCount = Math.max(0, effectiveTargetCount - permissionBlockedCount);
  const permissionBlockedPreview = useMemo(
    () =>
      permissionBlockedTargets
        .slice(0, 3)
        .map((group) => group.name.trim() || group.chatId)
        .join(', '),
    [permissionBlockedTargets]
  );
  const hasTargets = effectiveTargetCount > 0;
  const templateIssues = useMemo(
    () => lintTemplate(composer.captionTemplate),
    [composer.captionTemplate]
  );
  const templateErrors = useMemo(
    () => templateIssues.filter((issue) => issue.level === 'error'),
    [templateIssues]
  );
  const templateWarnings = useMemo(
    () => templateIssues.filter((issue) => issue.level === 'warning'),
    [templateIssues]
  );
  const hasTemplateEmptyWarning = useMemo(
    () => templateWarnings.some((issue) => issue.message.includes('đang trống')),
    [templateWarnings]
  );
  const displayedTemplateWarnings = useMemo(
    () => templateWarnings.filter((issue) => !issue.message.includes('đang trống')),
    [templateWarnings]
  );
  const hasTemplateErrors = templateErrors.length > 0;

  const hasContent = Boolean(
    composer.imagePath ||
      composer.captionTemplate.trim() ||
      composer.introText.trim() ||
      composer.titleText.trim() ||
      composer.footerText.trim() ||
      composer.plainTextFallback.trim()
  );
  const hasConnectionConfig = Boolean(settings?.baseUrl && settings?.apiKey && settings?.instanceName);
  const isConnected = badgeState === 'connected' || settings?.providerMode === 'mock';
  const canSend = hasConnectionConfig && isConnected && hasTargets && hasContent && !hasTemplateErrors;
  const missingReadinessReasons = useMemo(() => {
    const reasons: string[] = [];
    if (!hasConnectionConfig) {
      reasons.push('thiếu cấu hình');
      return reasons;
    }
    if (!isConnected) {
      reasons.push('chưa kết nối instance');
    }
    if (!hasTargets) {
      reasons.push('chưa có nhóm hợp lệ');
    }
    if (!hasContent) {
      reasons.push('chưa có nội dung');
    }
    if (hasTemplateErrors) {
      reasons.push('lỗi mẫu nội dung');
    }
    return reasons;
  }, [hasConnectionConfig, hasContent, hasTargets, hasTemplateErrors, isConnected]);
  const executionDisabledReason = useMemo(() => {
    if (campaignStore.stopping) {
      return 'Chiến dịch đang dừng. Vui lòng chờ hệ thống hoàn tất trạng thái trước khi thao tác mới.';
    }
    if (campaignStore.running) {
      return campaignStore.paused
        ? 'Chiến dịch đang tạm dừng. Hãy tiếp tục hoặc dừng chiến dịch hiện tại.'
        : 'Chiến dịch đang chạy. Hãy tạm dừng hoặc dừng chiến dịch hiện tại trước khi thao tác mới.';
    }
    if (!hasConnectionConfig) {
      return 'Thiếu cấu hình kết nối (Base URL / API Key / Instance Name).';
    }
    if (!isConnected) {
      return 'Chưa kết nối instance. Hãy mở cài đặt kết nối (icon bánh răng) và bấm "Kết nối".';
    }
    if (!hasTargets) {
      return 'Chưa có nhóm nhận hợp lệ.';
    }
    if (!hasContent) {
      return 'Chưa có nội dung gửi.';
    }
    if (hasTemplateErrors) {
      return `Mẫu nội dung có lỗi: ${templateErrors[0]?.message ?? 'Vui lòng kiểm tra lại template.'}`;
    }
    return null;
  }, [
    campaignStore.paused,
    campaignStore.running,
    campaignStore.stopping,
    hasConnectionConfig,
    hasContent,
    hasTemplateErrors,
    hasTargets,
    isConnected,
    templateErrors
  ]);
  const executionBlocked = executionDisabledReason !== null;
  const executionBadgeHint = useMemo(() => {
    if (campaignStore.running || campaignStore.stopping) {
      return null;
    }
    if (!hasConnectionConfig) {
      return 'thiếu cấu hình';
    }
    if (!isConnected) {
      return 'chưa kết nối';
    }
    if (!hasTargets) {
      return 'chưa có nhóm hợp lệ';
    }
    if (!hasContent) {
      return 'chưa có nội dung';
    }
    if (hasTemplateErrors) {
      return 'lỗi mẫu nội dung';
    }
    return null;
  }, [
    campaignStore.running,
    campaignStore.stopping,
    hasConnectionConfig,
    hasContent,
    hasTargets,
    hasTemplateErrors,
    isConnected
  ]);

  const warningThresholdEnabled = campaignStore.config.warningThreshold > 0;
  const warningThresholdHit =
    warningThresholdEnabled && effectiveTargetCount > campaignStore.config.warningThreshold;
  const warningIntensity = warningThresholdEnabled
    ? effectiveTargetCount / campaignStore.config.warningThreshold
    : 0;
  const highVolumeRisk = warningThresholdHit && warningIntensity >= 3;
  const listModeLabel = campaignStore.config.whitelistMode ? 'Danh sách cho phép' : 'Danh sách chặn';
  const chatIdCount = campaignStore.config.blacklist.length;
  const activeProfile = useMemo(() => {
    const cfg = campaignStore.config;
    if (
      cfg.randomDelayMinMs === 4000 &&
      cfg.randomDelayMaxMs === 8000 &&
      cfg.maxAttempts === 3
    ) {
      return 'safe';
    }
    if (
      cfg.randomDelayMinMs === 800 &&
      cfg.randomDelayMaxMs === 1500 &&
      cfg.maxAttempts === 1
    ) {
      return 'fast';
    }
    if (
      cfg.randomDelayMinMs === 2000 &&
      cfg.randomDelayMaxMs === 6000 &&
      cfg.maxAttempts === 2
    ) {
      return 'balanced';
    }
    return 'custom';
  }, [campaignStore.config]);

  const readiness = [
    {
      label: 'Kết nối',
      state: isConnected ? 'đạt' : 'thiếu',
      variant: (isConnected ? 'success' : 'outline') as 'success' | 'outline'
    },
    {
      label: 'Nhóm nhận',
      state: hasTargets ? 'đạt' : 'thiếu',
      variant: (hasTargets ? 'success' : 'outline') as 'success' | 'outline'
    },
    {
      label: 'Nội dung',
      state: hasContent ? 'đạt' : 'thiếu',
      variant: (hasContent ? 'success' : 'outline') as 'success' | 'outline'
    },
    {
      label: 'Mẫu hợp lệ',
      state: hasTemplateErrors ? 'lỗi' : hasTemplateEmptyWarning ? 'trống' : 'đạt',
      variant: (hasTemplateErrors
        ? 'destructive'
        : hasTemplateEmptyWarning
          ? 'secondary'
          : 'success') as 'destructive' | 'secondary' | 'success'
    }
  ];

  useEffect(() => {
    const source = composer.contentSource;
    if (!source) {
      return;
    }

    if (lastLoadedAtRef.current === source.loadedAt) {
      return;
    }
    lastLoadedAtRef.current = source.loadedAt;

    setCampaignName((prev) => {
      const normalizedPrev = prev.trim();
      const shouldAutoUpdate =
        !normalizedPrev || isAutoGeneratedCampaignName(normalizedPrev);
      if (!shouldAutoUpdate) {
        return prev;
      }
      return buildCampaignNameFromSource(source.campaignName);
    });
  }, [composer.contentSource]);

  const openConfirmWithValidation = async (nextDryRun: boolean) => {
    if (controlsDisabled) {
      return;
    }

    if (!canSend) {
      const missing: string[] = [];
      if (!hasConnectionConfig) {
        missing.push('cấu hình kết nối');
      } else if (!isConnected) {
        missing.push('kết nối instance');
      }
      if (!hasTargets) missing.push('nhóm nhận');
      if (!hasContent) missing.push('nội dung');
      if (hasTemplateErrors) missing.push('mẫu nội dung hợp lệ');
      pushUiLog({
        level: 'warn',
        message: `Chưa thể gửi. Thiếu: ${missing.join(', ')}.`
      });
      if (hasTemplateErrors && templateErrors[0]) {
        pushUiLog({
          level: 'warn',
          message: `Lỗi mẫu nội dung: ${templateErrors[0].message}`
        });
      }
      return;
    }

    if (!campaignName.trim()) {
      pushUiLog({
        level: 'warn',
        message: 'Tên chiến dịch không được để trống.'
      });
      return;
    }

    let duplicateWarning: string | null = null;
    if (!nextDryRun) {
      try {
        const duplicatePreview = await campaignStore.previewDuplicateWarning({
          groups,
          selectedIds,
          composer
        });
        duplicateWarning = duplicatePreview.warning;
      } catch (error) {
        const message = error instanceof Error ? error.message : 'Không thể kiểm tra trùng chiến dịch';
        pushUiLog({
          level: 'warn',
          message
        });
      }
    } else {
      setConfirmDuplicateWarning(null);
    }

    setConfirmDuplicateWarning(duplicateWarning);
    setDryRun(nextDryRun);
    setConfirmOpen(true);
  };

  const onConfirm = async () => {
    if (!settings || !canSend) {
      return;
    }
    if (hasTemplateErrors && templateErrors[0]) {
      pushUiLog({
        level: 'warn',
        message: `Lỗi mẫu nội dung: ${templateErrors[0].message}`
      });
      return;
    }

    const normalizedCampaignName = campaignName.trim();
    if (!normalizedCampaignName) {
      pushUiLog({
        level: 'warn',
        message: 'Tên chiến dịch không được để trống.'
      });
      return;
    }

    if (normalizedCampaignName !== campaignName) {
      setCampaignName(normalizedCampaignName);
    }

    try {
      await campaignStore.startCampaign({
        settings,
        groups,
        selectedIds,
        composer,
        dryRun,
        name: normalizedCampaignName
      });

      setCampaignName(buildCampaignName());
      setConfirmOpen(false);
    } catch (error) {
      const message =
        error instanceof Error
          ? error.message
          : typeof error === 'string'
            ? error
            : 'Không thể chạy chiến dịch';
      pushUiLog({
        level: 'error',
        message: `Gửi thất bại: ${message}`
      });
    }
  };

  const applyProfile = (profile: 'safe' | 'balanced' | 'fast') => {
    if (controlsDisabled) return;
    if (profile === 'safe') {
      campaignStore.setConfig({
        randomDelayMinMs: 4000,
        randomDelayMaxMs: 8000,
        maxAttempts: 3
      });
      return;
    }
    if (profile === 'fast') {
      campaignStore.setConfig({
        randomDelayMinMs: 800,
        randomDelayMaxMs: 1500,
        maxAttempts: 1
      });
      return;
    }
    campaignStore.setConfig({
      randomDelayMinMs: 2000,
      randomDelayMaxMs: 6000,
      maxAttempts: 2
    });
  };

  const updateDelayMin = (raw: string) => {
    const next = sanitizeInt(Number(raw), campaignStore.config.randomDelayMinMs, 0);
    campaignStore.setConfig({
      randomDelayMinMs: next,
      randomDelayMaxMs: Math.max(next, campaignStore.config.randomDelayMaxMs)
    });
  };

  const updateDelayMax = (raw: string) => {
    const next = sanitizeInt(Number(raw), campaignStore.config.randomDelayMaxMs, 0);
    campaignStore.setConfig({
      randomDelayMinMs: Math.min(campaignStore.config.randomDelayMinMs, next),
      randomDelayMaxMs: next
    });
  };

  const commitBlacklistInput = () => {
    if (controlsDisabled) {
      return;
    }
    const { validChatIds, invalidTokens } = parseChatIds(blacklistInput);
    if (invalidTokens.length > 0) {
      const preview = invalidTokens.slice(0, 3).join(', ');
      const more = invalidTokens.length > 3 ? ` +${invalidTokens.length - 3}` : '';
      pushUiLog({
        level: 'warn',
        message: `Bỏ qua ${invalidTokens.length} giá trị không hợp lệ (chỉ nhận chat id dạng ...@g.us): ${preview}${more}`
      });
    }
    if (validChatIds.length === 0) {
      if (blacklistInput.trim()) {
        setBlacklistInput('');
      }
      return;
    }
    const merged = Array.from(
      new Set([
        ...campaignStore.config.blacklist.map((item) => normalizeChatId(item)),
        ...validChatIds
      ])
    ).sort((a, b) => a.localeCompare(b, 'en', { sensitivity: 'base' }));
    campaignStore.setConfig({ blacklist: merged });
    setBlacklistInput('');
  };

  const onBlacklistInputKeyDown = (event: ReactKeyboardEvent<HTMLInputElement>) => {
    if (event.key !== 'Enter') {
      return;
    }
    event.preventDefault();
    commitBlacklistInput();
  };

  const removeBlacklistItem = (chatId: string) => {
    if (controlsDisabled) {
      return;
    }
    const normalizedTarget = normalizeChatId(chatId);
    campaignStore.setConfig({
      blacklist: campaignStore.config.blacklist.filter(
        (item) => normalizeChatId(item) !== normalizedTarget
      )
    });
  };

  return (
    <Card>
      <CardHeader className={panelTokens.cardHeader}>
        <CardTitle>Vận hành</CardTitle>
      </CardHeader>
      <CardContent className={panelTokens.cardContent}>
        {campaignStore.duplicateWarning && (
          <div className="rounded-lg border border-warning/40 bg-warning/10 p-3 text-sm text-warning">
            {campaignStore.duplicateWarning}
          </div>
        )}

        {warningThresholdHit && (
          <div
            className={
              highVolumeRisk
                ? 'flex items-center gap-2 rounded-lg border border-warning/40 bg-warning/10 p-3 text-sm text-warning'
                : 'flex items-center gap-2 rounded-lg border border-primary/30 bg-primary/10 p-3 text-sm text-primary'
            }
          >
            <AlertTriangle className="h-4 w-4" />
            {highVolumeRisk
              ? `Khối lượng gửi rất lớn: ${effectiveTargetCount} nhóm (ngưỡng ${campaignStore.config.warningThreshold}). Nên chia nhỏ theo nhiều đợt để an toàn hơn.`
              : `Khối lượng gửi lớn: ${effectiveTargetCount} nhóm (ngưỡng ${campaignStore.config.warningThreshold}). Nên chạy thử trước khi gửi thật.`}
          </div>
        )}
        {permissionBlockedCount > 0 ? (
          <div className="rounded-lg border border-warning/40 bg-warning/10 p-3 text-sm text-warning">
            <p className="font-medium">
              Dự kiến bỏ qua {permissionBlockedCount}/{effectiveTargetCount} nhóm do không có quyền
              gửi.
            </p>
            <p className="mt-1">
              Có thể xử lý tối đa {permissionAllowedCount} nhóm.
              {permissionBlockedPreview
                ? ` Ví dụ: ${permissionBlockedPreview}${
                    permissionBlockedCount > 3 ? ` +${permissionBlockedCount - 3} nhóm khác.` : '.'
                  }`
                : ''}
            </p>
          </div>
        ) : null}

        {hasTemplateErrors ? (
          <div className="rounded-lg border border-destructive/40 bg-destructive/10 p-3 text-sm text-destructive">
            <p className="font-medium">Mẫu nội dung có lỗi cú pháp.</p>
            <p className="mt-1">{templateErrors[0]?.message}</p>
          </div>
        ) : null}
        {!hasTemplateErrors && displayedTemplateWarnings.length > 0 ? (
          <div className="rounded-lg border border-warning/40 bg-warning/10 p-3 text-sm text-warning">
            <p className="font-medium">Lưu ý trước khi gửi</p>
            <p className="mt-1">{displayedTemplateWarnings[0]?.message}</p>
          </div>
        ) : null}

        <div className={panelTokens.section}>
          <p className={panelTokens.sectionTitle}>Trạng thái sẵn sàng</p>
          <div className="flex flex-wrap items-center gap-2">
            {readiness.map((item) => (
              <Badge
                key={item.label}
                variant={item.variant}
                className={item.variant === 'outline' ? 'border-border/55 bg-background/40 text-muted-foreground' : ''}
              >
                {item.label} {item.state}
              </Badge>
            ))}
          </div>
          {!canSend && !campaignStore.running ? (
            <p className="text-sm text-muted-foreground">
              Thiếu điều kiện gửi: {missingReadinessReasons.join(', ') || executionBadgeHint || executionDisabledReason?.replace(/\.$/, '') || 'vui lòng kiểm tra lại điều kiện gửi'}.
            </p>
          ) : null}
        </div>

        <div className={panelTokens.section}>
          <p className={panelTokens.sectionTitle}>Chiến dịch</p>
          <Label className={panelTokens.fieldLabel}>Tên chiến dịch</Label>
          <div className="flex gap-2">
            <Input
              value={campaignName}
              onChange={(e) => setCampaignName(e.target.value)}
              disabled={controlsDisabled}
              className={panelTokens.control}
            />
            <Button
              type="button"
              variant="outline"
              onClick={() => setCampaignName(buildCampaignName())}
              disabled={controlsDisabled}
              className={panelTokens.control}
            >
              <RefreshCw className="h-3.5 w-3.5" />
            </Button>
          </div>
        </div>

        <div className={panelTokens.section}>
          <p className={panelTokens.sectionTitle}>Chiến lược gửi</p>
          <Label className={panelTokens.fieldLabel}>Hồ sơ gửi</Label>
          <div className="grid grid-cols-3 gap-2">
            <Button
              type="button"
              variant={activeProfile === 'safe' ? 'default' : 'outline'}
              onClick={() => applyProfile('safe')}
              disabled={controlsDisabled}
              className={panelTokens.control}
            >
              An toàn
            </Button>
            <Button
              type="button"
              variant={activeProfile === 'balanced' ? 'default' : 'outline'}
              onClick={() => applyProfile('balanced')}
              disabled={controlsDisabled}
              className={panelTokens.control}
            >
              Cân bằng
            </Button>
            <Button
              type="button"
              variant={activeProfile === 'fast' ? 'default' : 'outline'}
              onClick={() => applyProfile('fast')}
              disabled={controlsDisabled}
              className={panelTokens.control}
            >
              Nhanh
            </Button>
          </div>
        </div>

        <div className={panelTokens.section}>
          <button
            type="button"
            className={`${panelTokens.control} flex w-full items-center justify-between border border-border/40 bg-background/35 px-3 text-left font-medium text-muted-foreground transition-colors hover:bg-muted/30`}
            onClick={() => setShowAdvanced((prev) => !prev)}
          >
            <span>Cấu hình nâng cao</span>
            <ChevronDown
              className={`h-4 w-4 shrink-0 transition-transform duration-200 ${
                showAdvanced ? 'rotate-180 text-foreground/80' : 'text-muted-foreground/70'
              }`}
            />
          </button>

          {showAdvanced ? (
            <div className="space-y-2 pt-1">
              <div className="grid grid-cols-2 gap-2">
                <div className="space-y-1">
                  <Label className={panelTokens.fieldLabel}>Trễ min (ms)</Label>
                  <Input
                    type="number"
                    value={campaignStore.config.randomDelayMinMs}
                    onChange={(e) => updateDelayMin(e.target.value)}
                    disabled={controlsDisabled}
                    className={panelTokens.control}
                  />
                </div>
                <div className="space-y-1">
                  <Label className={panelTokens.fieldLabel}>Trễ max (ms)</Label>
                  <Input
                    type="number"
                    value={campaignStore.config.randomDelayMaxMs}
                    onChange={(e) => updateDelayMax(e.target.value)}
                    disabled={controlsDisabled}
                    className={panelTokens.control}
                  />
                </div>
                <div className="space-y-1">
                  <Label className={panelTokens.fieldLabel}>Dừng mỗi N nhóm</Label>
                  <Input
                    type="number"
                    value={campaignStore.config.pauseEvery}
                    onChange={(e) =>
                      campaignStore.setConfig({
                        pauseEvery: sanitizeInt(Number(e.target.value), campaignStore.config.pauseEvery, 0)
                      })
                    }
                    disabled={controlsDisabled}
                    className={panelTokens.control}
                  />
                </div>
                <div className="space-y-1">
                  <Label className={panelTokens.fieldLabel}>Dừng (ms)</Label>
                  <Input
                    type="number"
                    value={campaignStore.config.pauseDurationMs}
                    onChange={(e) =>
                      campaignStore.setConfig({
                        pauseDurationMs: sanitizeInt(
                          Number(e.target.value),
                          campaignStore.config.pauseDurationMs,
                          0
                        )
                      })
                    }
                    disabled={controlsDisabled}
                    className={panelTokens.control}
                  />
                </div>
                <div className="space-y-1">
                  <Label className={panelTokens.fieldLabel}>Thử lại tối đa</Label>
                  <Input
                    type="number"
                    value={campaignStore.config.maxAttempts}
                    onChange={(e) =>
                      campaignStore.setConfig({
                        maxAttempts: sanitizeInt(Number(e.target.value), campaignStore.config.maxAttempts, 1)
                      })
                    }
                    disabled={controlsDisabled}
                    className={panelTokens.control}
                  />
                </div>
                <div className="space-y-1">
                  <Label className={panelTokens.fieldLabel}>Ngưỡng cảnh báo</Label>
                  <Input
                    type="number"
                    value={campaignStore.config.warningThreshold}
                    placeholder="0 = tắt"
                    onChange={(e) =>
                      campaignStore.setConfig({
                        warningThreshold: sanitizeInt(
                          Number(e.target.value),
                          campaignStore.config.warningThreshold,
                          0
                        )
                      })
                    }
                    disabled={controlsDisabled}
                    className={panelTokens.control}
                  />
                </div>
              </div>

              <div className={panelTokens.section}>
                <div className="flex items-center justify-between">
                  <Label className={panelTokens.fieldLabel}>Chế độ danh sách cho phép</Label>
                  <Checkbox
                    checked={campaignStore.config.whitelistMode}
                    onCheckedChange={(value) => campaignStore.setConfig({ whitelistMode: value === true })}
                    disabled={controlsDisabled}
                  />
                </div>
                <div className="space-y-1">
                  <Label className={panelTokens.fieldLabel}>
                    {listModeLabel} ({chatIdCount})
                  </Label>
                  <Input
                    placeholder="Nhập chat id, nhấn Enter để thêm"
                    value={blacklistInput}
                    onChange={(e) => setBlacklistInput(e.target.value)}
                    onKeyDown={onBlacklistInputKeyDown}
                    onBlur={commitBlacklistInput}
                    disabled={controlsDisabled}
                    className={panelTokens.control}
                  />
                  <p className="text-xs text-muted-foreground">
                    Chỉ nhận chat id nhóm dạng <code className="font-mono">...@g.us</code>. Có thể dán nhiều id, phân tách bằng dấu phẩy, khoảng trắng hoặc xuống dòng rồi nhấn Enter.
                  </p>
                  {campaignStore.config.blacklist.length > 0 ? (
                    <div className="max-h-72 overflow-y-auto pr-1 pt-1">
                      <div className="flex flex-wrap gap-2">
                        {campaignStore.config.blacklist.map((chatId) => (
                          <div
                            key={chatId}
                            className="inline-flex min-h-10 max-w-full items-center gap-2 rounded-full border border-border/40 bg-background/50 px-3 py-1.5 text-xs text-foreground"
                          >
                            <span className="min-w-0">
                              <span
                                className="block max-w-[230px] truncate text-[11px] font-medium leading-4 text-foreground"
                                title={groupNameByChatId.get(normalizeChatId(chatId)) ?? 'Chưa tìm thấy tên nhóm trong cache hiện tại'}
                              >
                                {groupNameByChatId.get(normalizeChatId(chatId)) ?? 'Nhóm chưa xác định'}
                              </span>
                              <span className="block max-w-[230px] truncate font-mono text-[11px] leading-4 text-muted-foreground">
                                {chatId}
                              </span>
                            </span>
                            <button
                              type="button"
                              className="inline-flex h-4 w-4 items-center justify-center rounded-full text-muted-foreground transition-colors hover:bg-muted hover:text-foreground"
                              onClick={() => removeBlacklistItem(chatId)}
                              disabled={controlsDisabled}
                              aria-label={`Xóa ${chatId}`}
                            >
                              <X className="h-3 w-3" />
                            </button>
                          </div>
                        ))}
                      </div>
                    </div>
                  ) : (
                    <p className="text-xs text-muted-foreground">Chưa có chat id trong danh sách.</p>
                  )}
                </div>
              </div>
            </div>
          ) : null}
        </div>

        <div className={panelTokens.section}>
          <div className="space-y-2">
            <div className="flex items-center justify-between gap-2">
              <p className="text-sm font-semibold text-foreground">Thực thi</p>
              <div className="flex items-center gap-2">
                {executionBadgeHint ? <Badge variant="warning">{executionBadgeHint}</Badge> : null}
                {campaignStore.running || campaignStore.stopping ? (
                  <Badge variant="warning">
                    {campaignStopping ? 'đang dừng' : campaignPaused ? 'tạm dừng' : 'đang chạy'}
                  </Badge>
                ) : (
                  <Badge variant="secondary">sẵn sàng</Badge>
                )}
              </div>
            </div>
            <div className="grid grid-cols-1 gap-1.5 sm:grid-cols-3">
              <div className="flex min-h-20 flex-col justify-between rounded-lg border border-border/25 bg-muted/10 px-3 py-2">
                <p className="text-[11px] text-foreground/70">Đã chọn</p>
                <p className="text-lg font-semibold leading-none text-foreground">
                  {selectedCount}
                </p>
              </div>
              <div className="flex min-h-20 flex-col justify-between rounded-lg border border-border/25 bg-muted/10 px-3 py-2">
                <p className="text-[11px] text-foreground/70">Hợp lệ theo danh sách</p>
                <p className="text-lg font-semibold leading-none text-foreground">
                  {effectiveTargetCount}
                </p>
              </div>
              <div className="flex min-h-20 flex-col justify-between rounded-lg border border-border/25 bg-muted/10 px-3 py-2">
                <p className="text-[11px] text-foreground/70">Có quyền gửi</p>
                <p className="text-lg font-semibold leading-none text-foreground">
                  {permissionAllowedCount}
                </p>
              </div>
            </div>
          </div>

          {campaignStore.running ? (
            <div className="grid grid-cols-1 gap-2 sm:grid-cols-2">
              <Button
                variant={campaignPaused ? 'default' : 'secondary'}
                onClick={() =>
                  campaignPaused
                    ? void campaignStore.resumeCampaign()
                    : void campaignStore.pauseCampaign()
                }
                disabled={!campaignStore.queue || campaignStopping}
                title={
                  campaignPaused
                    ? 'Tiếp tục gửi từ vị trí đang tạm dừng'
                    : 'Tạm dừng sau khi xử lý xong nhóm hiện tại'
                }
                className={panelTokens.control}
              >
                {campaignPaused ? 'Tiếp tục' : 'Tạm dừng'}
              </Button>
              <Button
                variant="destructive"
                onClick={() => campaignStore.stopCampaign()}
                disabled={!campaignStore.running || campaignStopping}
                className={panelTokens.control}
              >
                {campaignStopping ? 'Đang dừng...' : 'Dừng khẩn cấp'}
              </Button>
            </div>
          ) : (
            <div className="grid grid-cols-1 gap-2 sm:grid-cols-2">
              <Button
                variant="secondary"
                onClick={() => void openConfirmWithValidation(true)}
                disabled={executionBlocked}
                title={executionDisabledReason ?? 'Chạy thử chiến dịch'}
                className={panelTokens.control}
              >
                Chạy thử
              </Button>
              <Button
                variant={executionBlocked ? 'secondary' : 'default'}
                onClick={() => void openConfirmWithValidation(false)}
                disabled={executionBlocked}
                title={executionDisabledReason ?? `Gửi tới ${effectiveTargetCount} nhóm`}
                className={
                  executionBlocked
                    ? `${panelTokens.control} font-semibold text-muted-foreground`
                    : `${panelTokens.control} font-semibold shadow-[0_8px_24px_-16px_hsl(var(--primary))]`
                }
              >
                Gửi
              </Button>
            </div>
          )}
          {campaignStore.running ? (
            <p className="text-sm text-muted-foreground">
              {campaignStopping
                ? 'Hệ thống đang dừng chiến dịch và hoàn tất trạng thái cuối. Vui lòng chờ trong giây lát.'
                : campaignPaused
                ? 'Chiến dịch đang tạm dừng. Bấm "Tiếp tục" để gửi tiếp từ nhóm kế tiếp.'
                : 'Chiến dịch đang gửi. Bạn có thể tạm dừng hoặc dừng khẩn cấp bất kỳ lúc nào.'}
            </p>
          ) : null}

          <div className="grid grid-cols-1 gap-2">
            <Button
              variant="outline"
              onClick={() => campaignStore.exportLatestCsv()}
              disabled={!campaignStore.activeCampaign}
              className={panelTokens.control}
            >
              Xuất CSV
            </Button>
          </div>
        </div>

        <AlertDialog
          open={confirmOpen}
          onOpenChange={(open) => {
            setConfirmOpen(open);
            if (!open) {
              setConfirmDuplicateWarning(null);
            }
          }}
        >
          <AlertDialogContent>
            <AlertDialogHeader>
              <AlertDialogTitle>{dryRun ? 'Xác nhận chạy thử' : 'Xác nhận gửi'}</AlertDialogTitle>
              <AlertDialogDescription>
                Chiến dịch <strong>{campaignName}</strong> sẽ xử lý <strong>{effectiveTargetCount}</strong> nhóm.
              </AlertDialogDescription>
              {!dryRun && confirmDuplicateWarning ? (
                <div className="rounded-md border border-warning/40 bg-warning/10 p-3 text-sm text-warning">
                  {confirmDuplicateWarning} Trùng theo tiêu chí: ảnh + nội dung + nhóm nhận.
                </div>
              ) : null}
              {permissionBlockedCount > 0 ? (
                <div className="rounded-md border border-warning/40 bg-warning/10 p-3 text-sm text-warning">
                  Dự kiến bỏ qua {permissionBlockedCount}/{effectiveTargetCount} nhóm do không có
                  quyền gửi. Có thể xử lý tối đa {permissionAllowedCount} nhóm.
                </div>
              ) : null}
            </AlertDialogHeader>
            <AlertDialogFooter>
              <AlertDialogCancel>Hủy</AlertDialogCancel>
              <AlertDialogAction onClick={onConfirm}>
                {dryRun
                  ? 'Bắt đầu chạy thử'
                  : confirmDuplicateWarning
                    ? 'Vẫn gửi'
                    : 'Bắt đầu gửi'}
              </AlertDialogAction>
            </AlertDialogFooter>
          </AlertDialogContent>
        </AlertDialog>
      </CardContent>
    </Card>
  );
}
