import { useEffect, useMemo, useRef, useState } from 'react';
import { AlertTriangle, RefreshCw } from 'lucide-react';
import dayjs from 'dayjs';
import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle
} from '@/components/ui/alert-dialog';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Checkbox } from '@/components/ui/checkbox';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { useCampaignStore } from '@/stores/use-campaign-store';
import { useActivityLogStore } from '@/stores/use-activity-log-store';
import { useComposerStore } from '@/stores/use-composer-store';
import { useGroupsStore } from '@/stores/use-groups-store';
import { useSettingsStore } from '@/stores/use-settings-store';

const buildCampaignName = (): string => `campaign-${dayjs().format('YYYYMMDD-HHmmss')}`;
const AUTO_CAMPAIGN_NAME_REGEX = /^campaign-\d{8}-\d{6}$/;
const isAutoGeneratedCampaignName = (value: string): boolean =>
  AUTO_CAMPAIGN_NAME_REGEX.test(value.trim());

const buildCampaignNameFromSource = (sourceName: string): string => {
  const normalized = sourceName.trim();
  if (!normalized) {
    return buildCampaignName();
  }
  return normalized;
};

const parseChatIds = (value: string): string[] =>
  value
    .split(/[\n,;\s]+/)
    .map((item) => item.trim())
    .filter(Boolean);

const sanitizeInt = (value: number, fallback: number, min = 0): number => {
  if (!Number.isFinite(value)) {
    return fallback;
  }
  return Math.max(min, Math.floor(value));
};

export function OperationsPanel(): JSX.Element {
  const [confirmOpen, setConfirmOpen] = useState(false);
  const [dryRun, setDryRun] = useState(true);
  const [confirmDuplicateWarning, setConfirmDuplicateWarning] = useState<string | null>(null);
  const [campaignName, setCampaignName] = useState(buildCampaignName());
  const [showAdvanced, setShowAdvanced] = useState(false);
  const lastLoadedAtRef = useRef<string | null>(null);

  const settings = useSettingsStore((state) => state.settings);
  const badgeState = useSettingsStore((state) => state.badgeState);
  const pushUiLog = useActivityLogStore((state) => state.pushUiLog);
  const groups = useGroupsStore((state) => state.groups);
  const selectedIdsSet = useGroupsStore((state) => state.selectedIds);
  const composer = useComposerStore();
  const campaignStore = useCampaignStore();

  const selectedIds = useMemo(() => Array.from(selectedIdsSet), [selectedIdsSet]);
  const selectedCount = selectedIds.length;
  const controlsDisabled = campaignStore.running || campaignStore.stopping;
  const campaignPaused = campaignStore.paused;
  const campaignStopping = campaignStore.stopping;
  const selectedGroups = useMemo(
    () => groups.filter((group) => selectedIdsSet.has(group.chatId)),
    [groups, selectedIdsSet]
  );
  const blockedIds = useMemo(
    () => new Set(campaignStore.config.blacklist),
    [campaignStore.config.blacklist]
  );
  const effectiveTargets = useMemo(
    () =>
      campaignStore.config.whitelistMode
        ? selectedGroups.filter((group) => blockedIds.has(group.chatId))
        : selectedGroups.filter((group) => !blockedIds.has(group.chatId)),
    [blockedIds, campaignStore.config.whitelistMode, selectedGroups]
  );
  const effectiveTargetCount = effectiveTargets.length;
  const hasTargets = effectiveTargetCount > 0;

  const hasContent = Boolean(
    composer.imagePath || composer.plainTextFallback.trim() || composer.captionTemplate.trim()
  );
  const hasConnectionConfig = Boolean(settings?.baseUrl && settings?.apiKey && settings?.instanceName);
  const isConnected = badgeState === 'connected' || settings?.providerMode === 'mock';
  const canSend = hasConnectionConfig && isConnected && hasTargets && hasContent;
  const executionDisabledReason = useMemo(() => {
    if (campaignStore.stopping) {
      return 'Chiến dịch đang dừng. Vui lòng chờ hệ thống hoàn tất trạng thái trước khi thao tác mới.';
    }
    if (campaignStore.running) {
      return campaignStore.paused
        ? 'Chiến dịch đang tạm dừng. Hãy tiếp tục hoặc dừng chiến dịch hiện tại.'
        : 'Chiến dịch đang chạy. Hãy tạm dừng hoặc dừng chiến dịch hiện tại trước khi thao tác mới.';
    }
    if (!hasConnectionConfig) {
      return 'Thiếu cấu hình kết nối (Base URL / API Key / Instance Name).';
    }
    if (!isConnected) {
      return 'Chưa kết nối instance. Hãy vào tab Kết nối và bấm "Kết nối".';
    }
    if (!hasTargets) {
      return 'Chưa có nhóm nhận hợp lệ.';
    }
    if (!hasContent) {
      return 'Chưa có nội dung gửi.';
    }
    return null;
  }, [
    campaignStore.paused,
    campaignStore.running,
    campaignStore.stopping,
    hasConnectionConfig,
    hasContent,
    hasTargets,
    isConnected
  ]);
  const executionBlocked = executionDisabledReason !== null;

  const warningThresholdEnabled = campaignStore.config.warningThreshold > 0;
  const warningThresholdHit =
    warningThresholdEnabled && effectiveTargetCount > campaignStore.config.warningThreshold;
  const warningIntensity = warningThresholdEnabled
    ? effectiveTargetCount / campaignStore.config.warningThreshold
    : 0;
  const highVolumeRisk = warningThresholdHit && warningIntensity >= 3;
  const listModeLabel = campaignStore.config.whitelistMode ? 'Danh sách cho phép' : 'Danh sách chặn';
  const chatIdCount = campaignStore.config.blacklist.length;
  const activeProfile = useMemo(() => {
    const cfg = campaignStore.config;
    if (
      cfg.randomDelayMinMs === 4000 &&
      cfg.randomDelayMaxMs === 8000 &&
      cfg.maxAttempts === 3
    ) {
      return 'safe';
    }
    if (
      cfg.randomDelayMinMs === 800 &&
      cfg.randomDelayMaxMs === 1500 &&
      cfg.maxAttempts === 1
    ) {
      return 'fast';
    }
    if (
      cfg.randomDelayMinMs === 2000 &&
      cfg.randomDelayMaxMs === 6000 &&
      cfg.maxAttempts === 2
    ) {
      return 'balanced';
    }
    return 'custom';
  }, [campaignStore.config]);

  const readiness = [
    { label: 'Kết nối', ok: isConnected },
    { label: 'Nhóm nhận', ok: hasTargets },
    { label: 'Nội dung', ok: hasContent }
  ];

  useEffect(() => {
    const source = composer.contentSource;
    if (!source) {
      return;
    }

    if (lastLoadedAtRef.current === source.loadedAt) {
      return;
    }
    lastLoadedAtRef.current = source.loadedAt;

    setCampaignName((prev) => {
      const normalizedPrev = prev.trim();
      const shouldAutoUpdate =
        !normalizedPrev || isAutoGeneratedCampaignName(normalizedPrev);
      if (!shouldAutoUpdate) {
        return prev;
      }
      return buildCampaignNameFromSource(source.campaignName);
    });
  }, [composer.contentSource]);

  const openConfirmWithValidation = async (nextDryRun: boolean) => {
    if (controlsDisabled) {
      return;
    }

    if (!canSend) {
      const missing: string[] = [];
      if (!hasConnectionConfig) {
        missing.push('cấu hình kết nối');
      } else if (!isConnected) {
        missing.push('kết nối instance');
      }
      if (!hasTargets) missing.push('nhóm nhận');
      if (!hasContent) missing.push('nội dung');
      pushUiLog({
        level: 'warn',
        message: `Chưa thể gửi. Thiếu: ${missing.join(', ')}.`
      });
      return;
    }

    if (!campaignName.trim()) {
      pushUiLog({
        level: 'warn',
        message: 'Tên chiến dịch không được để trống.'
      });
      return;
    }

    let duplicateWarning: string | null = null;
    if (!nextDryRun) {
      try {
        const duplicatePreview = await campaignStore.previewDuplicateWarning({
          groups,
          selectedIds,
          composer
        });
        duplicateWarning = duplicatePreview.warning;
      } catch (error) {
        const message = error instanceof Error ? error.message : 'Không thể kiểm tra trùng chiến dịch';
        pushUiLog({
          level: 'warn',
          message
        });
      }
    } else {
      setConfirmDuplicateWarning(null);
    }

    setConfirmDuplicateWarning(duplicateWarning);
    setDryRun(nextDryRun);
    setConfirmOpen(true);
  };

  const onConfirm = async () => {
    if (!settings || !canSend) {
      return;
    }

    const normalizedCampaignName = campaignName.trim();
    if (!normalizedCampaignName) {
      pushUiLog({
        level: 'warn',
        message: 'Tên chiến dịch không được để trống.'
      });
      return;
    }

    if (normalizedCampaignName !== campaignName) {
      setCampaignName(normalizedCampaignName);
    }

    try {
      await campaignStore.startCampaign({
        settings,
        groups,
        selectedIds,
        composer,
        dryRun,
        name: normalizedCampaignName
      });

      setCampaignName(buildCampaignName());
      setConfirmOpen(false);
    } catch (error) {
      const message =
        error instanceof Error
          ? error.message
          : typeof error === 'string'
            ? error
            : 'Không thể chạy chiến dịch';
      pushUiLog({
        level: 'error',
        message: `Gửi thất bại: ${message}`
      });
    }
  };

  const applyProfile = (profile: 'safe' | 'balanced' | 'fast') => {
    if (controlsDisabled) return;
    if (profile === 'safe') {
      campaignStore.setConfig({
        randomDelayMinMs: 4000,
        randomDelayMaxMs: 8000,
        maxAttempts: 3
      });
      return;
    }
    if (profile === 'fast') {
      campaignStore.setConfig({
        randomDelayMinMs: 800,
        randomDelayMaxMs: 1500,
        maxAttempts: 1
      });
      return;
    }
    campaignStore.setConfig({
      randomDelayMinMs: 2000,
      randomDelayMaxMs: 6000,
      maxAttempts: 2
    });
  };

  const updateDelayMin = (raw: string) => {
    const next = sanitizeInt(Number(raw), campaignStore.config.randomDelayMinMs, 0);
    campaignStore.setConfig({
      randomDelayMinMs: next,
      randomDelayMaxMs: Math.max(next, campaignStore.config.randomDelayMaxMs)
    });
  };

  const updateDelayMax = (raw: string) => {
    const next = sanitizeInt(Number(raw), campaignStore.config.randomDelayMaxMs, 0);
    campaignStore.setConfig({
      randomDelayMinMs: Math.min(campaignStore.config.randomDelayMinMs, next),
      randomDelayMaxMs: next
    });
  };

  return (
    <Card>
      <CardHeader className="pb-3">
        <CardTitle>Vận hành</CardTitle>
      </CardHeader>
      <CardContent className="space-y-3">
        {campaignStore.duplicateWarning && (
          <div className="rounded-md border border-warning/40 bg-warning/10 p-2 text-xs text-warning">
            {campaignStore.duplicateWarning}
          </div>
        )}

        {warningThresholdHit && (
          <div
            className={
              highVolumeRisk
                ? 'flex items-center gap-2 rounded-md border border-warning/40 bg-warning/10 p-2 text-xs text-warning'
                : 'flex items-center gap-2 rounded-md border border-primary/30 bg-primary/10 p-2 text-xs text-primary'
            }
          >
            <AlertTriangle className="h-4 w-4" />
            {highVolumeRisk
              ? `Khối lượng gửi rất lớn: ${effectiveTargetCount} nhóm (ngưỡng ${campaignStore.config.warningThreshold}). Nên chia nhỏ theo nhiều đợt để an toàn hơn.`
              : `Khối lượng gửi lớn: ${effectiveTargetCount} nhóm (ngưỡng ${campaignStore.config.warningThreshold}). Nên chạy thử trước khi gửi thật.`}
          </div>
        )}

        <div className="space-y-2 rounded-md border border-border/70 bg-muted/20 p-3">
          <p className="text-xs font-medium text-muted-foreground">Trạng thái sẵn sàng</p>
          <div className="flex flex-wrap items-center gap-2">
          {readiness.map((item) => (
            <Badge key={item.label} variant={item.ok ? 'success' : 'warning'}>
              {item.label}: {item.ok ? 'đạt' : 'thiếu'}
            </Badge>
          ))}
          </div>
          {!canSend && !campaignStore.running ? (
            <p className="text-xs text-muted-foreground">
              Thiếu điều kiện gửi: cần cấu hình + kết nối instance, nhóm nhận và nội dung.
            </p>
          ) : null}
        </div>

        <div className="space-y-2 rounded-md border border-border/70 bg-card/60 p-3">
          <p className="text-xs font-medium text-muted-foreground">Chiến dịch</p>
          <Label>Tên chiến dịch</Label>
          <div className="flex gap-2">
            <Input
              value={campaignName}
              onChange={(e) => setCampaignName(e.target.value)}
              disabled={controlsDisabled}
            />
            <Button
              type="button"
              variant="outline"
              onClick={() => setCampaignName(buildCampaignName())}
              disabled={controlsDisabled}
            >
              <RefreshCw className="h-3.5 w-3.5" />
            </Button>
          </div>
        </div>

        <div className="space-y-3 rounded-md border border-border/70 bg-card/60 p-3">
          <p className="text-xs font-medium text-muted-foreground">Chiến lược gửi</p>
          <Label>Hồ sơ gửi</Label>
          <div className="grid grid-cols-3 gap-2">
            <Button
              type="button"
              variant={activeProfile === 'safe' ? 'default' : 'outline'}
              onClick={() => applyProfile('safe')}
              disabled={controlsDisabled}
            >
              An toàn
            </Button>
            <Button
              type="button"
              variant={activeProfile === 'balanced' ? 'default' : 'outline'}
              onClick={() => applyProfile('balanced')}
              disabled={controlsDisabled}
            >
              Cân bằng
            </Button>
            <Button
              type="button"
              variant={activeProfile === 'fast' ? 'default' : 'outline'}
              onClick={() => applyProfile('fast')}
              disabled={controlsDisabled}
            >
              Nhanh
            </Button>
          </div>
        </div>

        <div className="space-y-2 rounded-md border border-border/70 bg-card/60 p-3">
          <button
            type="button"
            className="w-full rounded-md border border-border/70 bg-muted/20 px-3 py-2 text-left text-xs font-medium text-muted-foreground transition-colors hover:bg-muted/40"
            onClick={() => setShowAdvanced((prev) => !prev)}
          >
            Cấu hình nâng cao {showAdvanced ? '▲' : '▼'}
          </button>

          {showAdvanced ? (
            <div className="space-y-3 pt-1">
              <div className="grid grid-cols-2 gap-2">
                <div className="space-y-1">
                  <Label>Trễ min (ms)</Label>
                  <Input
                    type="number"
                    value={campaignStore.config.randomDelayMinMs}
                    onChange={(e) => updateDelayMin(e.target.value)}
                    disabled={controlsDisabled}
                  />
                </div>
                <div className="space-y-1">
                  <Label>Trễ max (ms)</Label>
                  <Input
                    type="number"
                    value={campaignStore.config.randomDelayMaxMs}
                    onChange={(e) => updateDelayMax(e.target.value)}
                    disabled={controlsDisabled}
                  />
                </div>
                <div className="space-y-1">
                  <Label>Dừng mỗi N nhóm</Label>
                  <Input
                    type="number"
                    value={campaignStore.config.pauseEvery}
                    onChange={(e) =>
                      campaignStore.setConfig({
                        pauseEvery: sanitizeInt(Number(e.target.value), campaignStore.config.pauseEvery, 0)
                      })
                    }
                    disabled={controlsDisabled}
                  />
                </div>
                <div className="space-y-1">
                  <Label>Dừng (ms)</Label>
                  <Input
                    type="number"
                    value={campaignStore.config.pauseDurationMs}
                    onChange={(e) =>
                      campaignStore.setConfig({
                        pauseDurationMs: sanitizeInt(
                          Number(e.target.value),
                          campaignStore.config.pauseDurationMs,
                          0
                        )
                      })
                    }
                    disabled={controlsDisabled}
                  />
                </div>
                <div className="space-y-1">
                  <Label>Thử lại tối đa</Label>
                  <Input
                    type="number"
                    value={campaignStore.config.maxAttempts}
                    onChange={(e) =>
                      campaignStore.setConfig({
                        maxAttempts: sanitizeInt(Number(e.target.value), campaignStore.config.maxAttempts, 1)
                      })
                    }
                    disabled={controlsDisabled}
                  />
                </div>
                <div className="space-y-1">
                  <Label>Ngưỡng cảnh báo</Label>
                  <Input
                    type="number"
                    value={campaignStore.config.warningThreshold}
                    placeholder="0 = tắt"
                    onChange={(e) =>
                      campaignStore.setConfig({
                        warningThreshold: sanitizeInt(
                          Number(e.target.value),
                          campaignStore.config.warningThreshold,
                          0
                        )
                      })
                    }
                    disabled={controlsDisabled}
                  />
                </div>
              </div>

              <div className="space-y-2 rounded-md border border-border/60 bg-muted/20 p-2.5">
                <div className="flex items-center justify-between">
                  <Label>Chế độ danh sách cho phép</Label>
                  <Checkbox
                    checked={campaignStore.config.whitelistMode}
                    onCheckedChange={(value) => campaignStore.setConfig({ whitelistMode: value === true })}
                    disabled={controlsDisabled}
                  />
                </div>
                <div className="space-y-1">
                  <Label>
                    {listModeLabel} ({chatIdCount})
                  </Label>
                  <Input
                    placeholder="chat1@g.us, chat2@g.us"
                    value={campaignStore.config.blacklist.join(',')}
                    onChange={(e) =>
                      campaignStore.setConfig({
                        blacklist: parseChatIds(e.target.value)
                      })
                    }
                    disabled={controlsDisabled}
                  />
                </div>
              </div>
            </div>
          ) : null}
        </div>

        <div className="space-y-3 rounded-md border border-border/70 bg-card/60 p-3">
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-2">
              <p className="text-xs font-medium text-muted-foreground">Thực thi</p>
              {campaignStore.running || campaignStore.stopping ? (
                <Badge variant="warning">
                  {campaignStopping ? 'đang dừng' : campaignPaused ? 'tạm dừng' : 'đang chạy'}
                </Badge>
              ) : (
                <Badge variant="secondary">nhàn rỗi</Badge>
              )}
            </div>
            <div className="flex items-center gap-2 text-xs text-muted-foreground">
              <span>Đã chọn {selectedCount}</span>
              <span>Hợp lệ</span>
              <Badge variant={hasTargets ? 'success' : 'warning'}>{effectiveTargetCount}</Badge>
            </div>
          </div>

          {campaignStore.running ? (
            <div className="grid grid-cols-1 gap-2 sm:grid-cols-2">
              <Button
                variant={campaignPaused ? 'default' : 'secondary'}
                onClick={() =>
                  campaignPaused
                    ? void campaignStore.resumeCampaign()
                    : void campaignStore.pauseCampaign()
                }
                disabled={!campaignStore.queue || campaignStopping}
                title={
                  campaignPaused
                    ? 'Tiếp tục gửi từ vị trí đang tạm dừng'
                    : 'Tạm dừng sau khi xử lý xong nhóm hiện tại'
                }
              >
                {campaignPaused ? 'Tiếp tục' : 'Tạm dừng'}
              </Button>
              <Button
                variant="destructive"
                onClick={() => campaignStore.stopCampaign()}
                disabled={!campaignStore.running || campaignStopping}
              >
                {campaignStopping ? 'Đang dừng...' : 'Dừng khẩn cấp'}
              </Button>
            </div>
          ) : (
            <div className="grid grid-cols-1 gap-2 sm:grid-cols-2">
              <Button
                variant="secondary"
                onClick={() => void openConfirmWithValidation(true)}
                disabled={executionBlocked}
                title={executionDisabledReason ?? 'Chạy thử chiến dịch'}
              >
                Chạy thử
              </Button>
              <Button
                onClick={() => void openConfirmWithValidation(false)}
                disabled={executionBlocked}
                title={executionDisabledReason ?? `Gửi tới ${effectiveTargetCount} nhóm`}
                className="font-semibold shadow-[0_8px_24px_-16px_hsl(var(--primary))]"
              >
                Gửi
              </Button>
            </div>
          )}
          {executionDisabledReason && !campaignStore.running ? (
            <p className="text-xs text-muted-foreground">{executionDisabledReason}</p>
          ) : campaignStore.running ? (
            <p className="text-xs text-muted-foreground">
              {campaignStopping
                ? 'Hệ thống đang dừng chiến dịch và hoàn tất trạng thái cuối. Vui lòng chờ trong giây lát.'
                : campaignPaused
                ? 'Chiến dịch đang tạm dừng. Bấm "Tiếp tục" để gửi tiếp từ nhóm kế tiếp.'
                : 'Chiến dịch đang gửi. Bạn có thể tạm dừng hoặc dừng khẩn cấp bất kỳ lúc nào.'}
            </p>
          ) : null}

          <div className="grid grid-cols-1 gap-2">
            <Button
              variant="outline"
              onClick={() => campaignStore.exportLatestCsv()}
              disabled={!campaignStore.activeCampaign}
            >
              Xuất CSV
            </Button>
          </div>
        </div>

        <AlertDialog
          open={confirmOpen}
          onOpenChange={(open) => {
            setConfirmOpen(open);
            if (!open) {
              setConfirmDuplicateWarning(null);
            }
          }}
        >
          <AlertDialogContent>
            <AlertDialogHeader>
              <AlertDialogTitle>{dryRun ? 'Xác nhận chạy thử' : 'Xác nhận gửi'}</AlertDialogTitle>
              <AlertDialogDescription>
                Chiến dịch <strong>{campaignName}</strong> sẽ xử lý <strong>{effectiveTargetCount}</strong> nhóm.
              </AlertDialogDescription>
              {!dryRun && confirmDuplicateWarning ? (
                <div className="rounded-md border border-warning/40 bg-warning/10 px-3 py-2 text-xs text-warning">
                  {confirmDuplicateWarning} Trùng theo tiêu chí: ảnh + nội dung + nhóm nhận.
                </div>
              ) : null}
            </AlertDialogHeader>
            <AlertDialogFooter>
              <AlertDialogCancel>Hủy</AlertDialogCancel>
              <AlertDialogAction onClick={onConfirm}>
                {dryRun
                  ? 'Bắt đầu chạy thử'
                  : confirmDuplicateWarning
                    ? 'Vẫn gửi'
                    : 'Bắt đầu gửi'}
              </AlertDialogAction>
            </AlertDialogFooter>
          </AlertDialogContent>
        </AlertDialog>
      </CardContent>
    </Card>
  );
}
