import dayjs from 'dayjs';

export const buildCampaignName = (): string => `campaign-${dayjs().format('YYYYMMDD-HHmmss')}`;
const AUTO_CAMPAIGN_NAME_REGEX = /^campaign-\d{8}-\d{6}$/;

export const isAutoGeneratedCampaignName = (value: string): boolean =>
  AUTO_CAMPAIGN_NAME_REGEX.test(value.trim());

export const buildCampaignNameFromSource = (sourceName: string): string => {
  const normalized = sourceName.trim();
  if (!normalized) {
    return buildCampaignName();
  }
  return normalized;
};

const GROUP_CHAT_ID_REGEX = /^[0-9a-z._:-]+@g\.us$/i;
export const normalizeChatId = (chatId: string): string => chatId.trim().toLowerCase();

export const parseChatIds = (value: string): { validChatIds: string[]; invalidTokens: string[] } => {
  const tokens = value
    .split(/[\n,;\s]+/)
    .map((item) => item.trim())
    .filter(Boolean);

  const validSet = new Set<string>();
  const invalidTokens: string[] = [];
  for (const token of tokens) {
    const normalized = normalizeChatId(token);
    if (GROUP_CHAT_ID_REGEX.test(normalized)) {
      validSet.add(normalized);
      continue;
    }
    invalidTokens.push(token);
  }

  return {
    validChatIds: Array.from(validSet),
    invalidTokens
  };
};

export const sanitizeInt = (value: number, fallback: number, min = 0): number => {
  if (!Number.isFinite(value)) {
    return fallback;
  }
  return Math.max(min, Math.floor(value));
};
