import { useEffect, useRef, useState, type KeyboardEvent as ReactKeyboardEvent } from 'react';
import { parseChatIds, buildCampaignName, buildCampaignNameFromSource, isAutoGeneratedCampaignName, normalizeChatId, sanitizeInt } from '@/components/composer/operations/utils';
import type { ComposerState } from '@/lib/types/domain';

interface CampaignConfigView {
  randomDelayMinMs: number;
  randomDelayMaxMs: number;
  pauseEvery: number;
  pauseDurationMs: number;
  maxAttempts: number;
  warningThreshold: number;
  blacklist: string[];
  whitelistMode: boolean;
}

interface CampaignStoreView {
  config: CampaignConfigView;
  setConfig: (config: Partial<CampaignConfigView>) => void;
}

export function useOperationsForm({
  composer,
  campaignStore,
  controlsDisabled,
  groupNameByChatId,
  pushUiLog
}: {
  composer: ComposerState & {
    contentSource?: { loadedAt: string; campaignName: string } | null;
  };
  campaignStore: CampaignStoreView;
  controlsDisabled: boolean;
  groupNameByChatId: Map<string, string>;
  pushUiLog: (payload: { level: 'info' | 'warn' | 'error' | 'success'; message: string }) => void;
}) {
  const [confirmOpen, setConfirmOpen] = useState(false);
  const [dryRun, setDryRun] = useState(true);
  const [confirmDuplicateWarning, setConfirmDuplicateWarning] = useState<string | null>(null);
  const [campaignName, setCampaignName] = useState(buildCampaignName());
  const [showAdvanced, setShowAdvanced] = useState(false);
  const [blacklistInput, setBlacklistInput] = useState('');
  const lastLoadedAtRef = useRef<string | null>(null);

  useEffect(() => {
    const source = composer.contentSource;
    if (!source) {
      return;
    }

    if (lastLoadedAtRef.current === source.loadedAt) {
      return;
    }
    lastLoadedAtRef.current = source.loadedAt;

    setCampaignName((prev) => {
      const normalizedPrev = prev.trim();
      const shouldAutoUpdate = !normalizedPrev || isAutoGeneratedCampaignName(normalizedPrev);
      if (!shouldAutoUpdate) {
        return prev;
      }
      return buildCampaignNameFromSource(source.campaignName);
    });
  }, [composer.contentSource]);

  const applyProfile = (profile: 'safe' | 'balanced' | 'fast') => {
    if (controlsDisabled) return;
    if (profile === 'safe') {
      campaignStore.setConfig({ randomDelayMinMs: 4000, randomDelayMaxMs: 8000, maxAttempts: 3 });
      return;
    }
    if (profile === 'fast') {
      campaignStore.setConfig({ randomDelayMinMs: 800, randomDelayMaxMs: 1500, maxAttempts: 1 });
      return;
    }
    campaignStore.setConfig({ randomDelayMinMs: 2000, randomDelayMaxMs: 6000, maxAttempts: 2 });
  };

  const updateDelayMin = (raw: string) => {
    const next = sanitizeInt(Number(raw), campaignStore.config.randomDelayMinMs, 0);
    campaignStore.setConfig({
      randomDelayMinMs: next,
      randomDelayMaxMs: Math.max(next, campaignStore.config.randomDelayMaxMs)
    });
  };

  const updateDelayMax = (raw: string) => {
    const next = sanitizeInt(Number(raw), campaignStore.config.randomDelayMaxMs, 0);
    campaignStore.setConfig({
      randomDelayMinMs: Math.min(campaignStore.config.randomDelayMinMs, next),
      randomDelayMaxMs: next
    });
  };

  const commitBlacklistInput = () => {
    if (controlsDisabled) {
      return;
    }

    const { validChatIds, invalidTokens } = parseChatIds(blacklistInput);
    if (invalidTokens.length > 0) {
      const preview = invalidTokens.slice(0, 3).join(', ');
      const more = invalidTokens.length > 3 ? ` +${invalidTokens.length - 3}` : '';
      pushUiLog({
        level: 'warn',
        message: `Bỏ qua ${invalidTokens.length} giá trị không hợp lệ (chỉ nhận chat id dạng ...@g.us): ${preview}${more}`
      });
    }

    if (validChatIds.length === 0) {
      if (blacklistInput.trim()) {
        setBlacklistInput('');
      }
      return;
    }

    const merged = Array.from(
      new Set([...campaignStore.config.blacklist.map((item) => normalizeChatId(item)), ...validChatIds])
    ).sort((a, b) => a.localeCompare(b, 'en', { sensitivity: 'base' }));

    campaignStore.setConfig({ blacklist: merged });
    setBlacklistInput('');
  };

  const onBlacklistInputKeyDown = (event: ReactKeyboardEvent<HTMLInputElement>) => {
    if (event.key !== 'Enter') {
      return;
    }
    event.preventDefault();
    commitBlacklistInput();
  };

  const removeBlacklistItem = (chatId: string) => {
    if (controlsDisabled) {
      return;
    }
    const normalizedTarget = normalizeChatId(chatId);
    campaignStore.setConfig({
      blacklist: campaignStore.config.blacklist.filter((item) => normalizeChatId(item) !== normalizedTarget)
    });
  };

  const blacklistItems = campaignStore.config.blacklist.map((chatId) => ({
    chatId,
    groupName: groupNameByChatId.get(normalizeChatId(chatId)) ?? 'Nhóm chưa xác định'
  }));

  return {
    confirmOpen,
    setConfirmOpen,
    dryRun,
    setDryRun,
    confirmDuplicateWarning,
    setConfirmDuplicateWarning,
    campaignName,
    setCampaignName,
    showAdvanced,
    setShowAdvanced,
    blacklistInput,
    setBlacklistInput,
    applyProfile,
    updateDelayMin,
    updateDelayMax,
    commitBlacklistInput,
    onBlacklistInputKeyDown,
    removeBlacklistItem,
    blacklistItems
  };
}
